server:
  port: 8080

spring:
  application:
    name: java-tutorial
  datasource:
    url: jdbc:h2:mem:tutorialdb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  h2:
    console:
      enabled: true
      path: /h2
  thymeleaf:
    cache: false
